# Pre-Commit documentation: https://pre-commit.com/
# Pre-Commit hooks: https://pre-commit.com/hooks.html
# Flake8 configuration: https://flake8.pycqa.org/en/latest/user/configuration.html
# Flake8 full listing of options: https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-version
# Black basics: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
default_language_version:
    python: python3
exclude: '(migrations|templates|static|fixtures)/.*'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-ast
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, master]
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      args: [--force-exclude=models.py]
      language_version: python3
      stages: [commit]
      entry: black
      exclude: '(migrations|templates|static|fixtures|models)/.*'
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      language_version: python3
      stages: [commit]
      entry: isort
      exclude: '(migrations|templates|static|fixtures)/.*'
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      language_version: python3
      stages: [commit]
      exclude: '(migrations|templates|static|fixtures)/.*'
