[tool.black]
line-length = 120
exclude = '''
(
  /(
      \.git             # Exclude a few common directories in the
    | venv
    | \.venv
    | migrations\/*
    | requirements\.txt
  )/
                     # The root of the project
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
skip = '.venv, venv, env, migrations, __init__.py'
src_paths = ["notes"]
